# Generated by Django 4.2.1 on 2023-05-13 19:37

import deal.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTime_UTC', deal.models.DateTimeUTCField(auto_now=True, null=True)),
                ('Update_DateTime_UTC', deal.models.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('Description', models.TextField(default='No Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('currency', models.CharField(default=' USD', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateTime_UTC', deal.models.DateTimeUTCField(auto_now_add=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data_joined')),
                ('Update_DateTime_UTC', deal.models.DateTimeUTCField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=15)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+962\\d{8}$')], verbose_name='phone no.')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True)),
                ('Date_Of_Birth', models.DateField(blank=True, max_length=8, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=deal.models.get_upload_path)),
                ('last_login', deal.models.DateTimeUTCField(auto_now=True, null=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('claimed_deal', models.ManyToManyField(blank=True, null=True, to='deal.deal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
