# Generated by Django 4.2.1 on 2023-05-07 14:24

import datetimeutc.fields
import deal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='data_joined')),
                ('last_login', datetimeutc.fields.DateTimeUTCField(auto_now=True, null=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTime_UTC', datetimeutc.fields.DateTimeUTCField(null=True)),
                ('Update_DateTime_UTC', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('Description', models.TextField(default='No Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('currency', models.CharField(default=' USD', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTime_UTC', datetimeutc.fields.DateTimeUTCField(null=True)),
                ('Update_DateTime_UTC', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('last_login', datetimeutc.fields.DateTimeUTCField(blank=True, null=True, verbose_name='Last Login')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=15)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone no.')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True)),
                ('Date_Of_Birth', models.DateField(max_length=8)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=deal.models.get_upload_path)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
