# Generated by Django 4.2.1 on 2023-05-03 20:02

import datetimeutc.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTime_UTC', datetimeutc.fields.DateTimeUTCField(null=True)),
                ('Update_DateTime_UTC', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'In Active'), ('DE', 'Deleted'), ('EXP', 'Expired')], default='ACT', max_length=3)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='phone no.')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=6, null=True)),
                ('Date_Of_Birth', models.DateField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
