# Generated by Django 4.2.1 on 2023-05-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='claimed_deal',
            field=models.ManyToManyField(blank=True, null=True, to='deal.deal'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone no.'),
        ),
    ]
