# Generated by Django 4.2.1 on 2023-05-07 14:56

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='DateTime_UTC',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True, null=True),
        ),
    ]
