# Generated by Django 4.2.1 on 2023-05-07 16:00

import datetimeutc.fields
import deal.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_alter_deal_datetime_utc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='DateTime_UTC',
            field=datetimeutc.fields.DateTimeUTCField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Server_DateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='Update_DateTime_UTC',
            field=datetimeutc.fields.DateTimeUTCField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='phone no.'),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=deal.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
