# Generated by Django 4.2.1 on 2023-05-03 20:28

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_rename_user_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Server_DateTime', models.DateTimeField(auto_now_add=True)),
                ('DateTime_UTC', datetimeutc.fields.DateTimeUTCField(null=True)),
                ('Update_DateTime_UTC', datetimeutc.fields.DateTimeUTCField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('Description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('INA', 'In Active'), ('DE', 'Deleted'), ('EXP', 'Expired')], default='ACT', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default='5', max_digits=9)),
                ('currency', models.CharField(default=' USD', max_length=3)),
            ],
        ),
    ]
