# Generated by Django 4.2.1 on 2023-05-10 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_alter_account_claimed_deal_alter_account_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{6}$')], verbose_name='phone no.'),
        ),
    ]
