# Generated by Django 4.2.1 on 2023-05-03 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_deals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
