# Generated by Django 4.2.1 on 2023-05-07 16:02

import datetimeutc.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_remove_user_profile_user_account_datetime_utc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='DateTime_UTC',
            field=datetimeutc.fields.DateTimeUTCField(auto_now_add=True, null=True),
        ),
    ]
