# Generated by Django 4.2.1 on 2023-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_rename_deals_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='400', max_digits=9),
        ),
    ]
