# Generated by Django 4.2.1 on 2023-05-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_alter_account_datetime_utc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.AddField(
            model_name='account',
            name='claimed_deal',
            field=models.ManyToManyField(to='deal.deal'),
        ),
    ]
