# Generated by Django 4.2.1 on 2023-05-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_alter_deal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In_Active', 'In Active'), ('Deleted', 'Deleted'), ('Expired', 'Expired')], default='Active', max_length=15),
        ),
    ]
