# Generated by Django 4.2.1 on 2023-05-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0008_user_profile_user_alter_deal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
