# Generated by Django 4.2.1 on 2023-05-06 18:22

import datetimeutc.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0010_alter_deal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='last_login',
            field=datetimeutc.fields.DateTimeUTCField(blank=True, null=True, verbose_name='Last Login'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.CharField(default=' USD', max_length=6),
        ),
    ]
